import mysql.connector
from mysql.connector import Error

#Inserir registros no banco 

try:
    con = mysql.connector.connect(host='localhost', port='3310', database='lojaok', user='root', password='c4rl0s91')

    
    inserir_venda = """INSERT INTO Venda (ID, CLIENTE_ID, DATA_VENDA) VALUES 
    (3996380,"21856","31/08/2021"), (4001825,"21856","05/09/2021"), (4010257,"21856","14/09/2021"),
    (4013258,"21856","16/09/2021"), (4020602,"21856","23/09/2021"), (3991743,"39550","26/08/2021"),
    (3966540,"39550","02/08/2021"), (3971036,"39550","05/08/2021"), (3973692,"39550","09/08/2021"),
    (3976647,"39550","11/08/2021"), (3976738,"39550","11/08/2021"), (3978424,"39550","12/08/2021"),
    (3981477,"39550","17/08/2021"), (3983610,"39550","18/08/2021"), (3984006,"39550","18/08/2021"),
    (3987719,"39550","23/08/2021"), (3989670,"39550","24/08/2021"), (3991746,"39550","26/08/2021"),
    (3992191,"39550","26/08/2021"), (3994929,"39550","30/08/2021"), (3998760,"39550","01/09/2021"),
    (4006602,"39550","09/09/2021"), (4011062,"39550","14/09/2021"), (4010256,"39550","14/09/2021"),
    (4014604,"39550","17/09/2021"), (4019409,"39550","22/09/2021"), (4024205,"39550","28/09/2021"),
    (4030567,"39550","04/10/2021"), (3979238,"44993","13/08/2021"), (3993373,"44993","27/08/2021"),
    (4007943,"44993","10/09/2021"), (4009140,"44993","13/09/2021"), (4005830,"49400","09/09/2021"),
    (4010241,"49400","14/09/2021"), (4010244,"49400","14/09/2021"), (4026958,"49400","29/09/2021")"""

    
    cursor = con.cursor()
    cursor.execute(inserir_venda)
    con.commit()
    print(cursor.rowcount, "Registros adicionados a tabela!")

except Error as erro:
    print("Falha ao inserir dados no SQL: {}".format(erro))
finally:
    if (con.is_connected()):
        cursor.close()
        con.close()
        print("Conex√£o ao MySQL finalizada")
